Models/BibleDataObject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bible_Application.Models
{
    public class BibleDataObject
    {
        public int BookSelection { get; set; }
        public int ChapterNumber { get; set; }
        public int VerseNumber { get; set; }
        public string VerseText { get; set; }
    }
}

Models/BibleDisplayObject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bible_Application.Models
{
    public class BibleDisplayObject
    {
        public string Testament { get; set; }

        [Required]
        public string Book { get; set; }

        [Required]
        [Range(0,1000)]
        public int Chapter { get; set; }

        [Required]
        [Range(0, 1000)]
        public int Verse { get; set; }

        [DisplayName("Text")]
        public string VerseText { get; set; }
    }
}

Models/BooksInBible.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bible_Application.Models
{
    public class BooksInBible
    {
        public List<Book> booksOfBible { get; set; }

        public BooksInBible()
        {
            this.booksOfBible = getBooksInBible();
        }

        public List<Book> getBooksInBible()
        {
            List<Book> booksList = new List<Book>();
            booksList.Add(new Book(1, "Genesis"));
            booksList.Add(new Book(2, "Exodus"));
            booksList.Add(new Book(3, "Leviticus"));
            booksList.Add(new Book(4, "Numbers"));
            booksList.Add(new Book(5, "Deuteronomy"));
            booksList.Add(new Book(6, "Joshua"));
            booksList.Add(new Book(7, "Judges"));
            booksList.Add(new Book(8, "Ruth"));
            booksList.Add(new Book(9, "1 Samuel"));
            booksList.Add(new Book(10, "2 Samuel"));
            booksList.Add(new Book(11, "1 Kings"));
            booksList.Add(new Book(12, "2 Kings"));
            booksList.Add(new Book(13, "1 Chronicles"));
            booksList.Add(new Book(14, "2 Chronicles"));
            booksList.Add(new Book(15, "Ezra"));
            booksList.Add(new Book(16, "Nehemiah"));
            booksList.Add(new Book(17, "Esther"));
            booksList.Add(new Book(18, "Job"));
            booksList.Add(new Book(19, "Psalm"));
            booksList.Add(new Book(20, "Proverbs"));
            booksList.Add(new Book(21, "Ecclesiastes"));
            booksList.Add(new Book(22, "Song of Songs"));
            booksList.Add(new Book(23, "Isaiah"));
            booksList.Add(new Book(24, "Jeremiah"));
            booksList.Add(new Book(25, "Lamentations"));
            booksList.Add(new Book(26, "Ezekiel"));
            booksList.Add(new Book(27, "Daniel"));
            booksList.Add(new Book(28, "Hosea"));
            booksList.Add(new Book(29, "Joel"));
            booksList.Add(new Book(30, "Amos"));
            booksList.Add(new Book(31, "Obadiah"));
            booksList.Add(new Book(32, "Jonah"));
            booksList.Add(new Book(33, "Micah"));
            booksList.Add(new Book(34, "Nahum"));
            booksList.Add(new Book(35, "Habakkuk"));
            booksList.Add(new Book(36, "Zephaniah"));
            booksList.Add(new Book(37, "Haggai"));
            booksList.Add(new Book(38, "Zechariah"));
            booksList.Add(new Book(39, "Malachi"));
            booksList.Add(new Book(40, "Matthew"));
            booksList.Add(new Book(41, "Mark"));
            booksList.Add(new Book(42, "Luke"));
            booksList.Add(new Book(43, "John"));
            booksList.Add(new Book(44, "Acts"));
            booksList.Add(new Book(45, "Romans"));
            booksList.Add(new Book(46, "1 Corinthians"));
            booksList.Add(new Book(47, "2 Corinthians"));
            booksList.Add(new Book(48, "Galatians"));
            booksList.Add(new Book(49, "Ephesians"));
            booksList.Add(new Book(50, "Philippians"));
            booksList.Add(new Book(51, "Colossians"));
            booksList.Add(new Book(52, "1 Thessalonians"));
            booksList.Add(new Book(53, "2 Thessalonians"));
            booksList.Add(new Book(54, "1 Timothy"));
            booksList.Add(new Book(55, "2 Timothy"));
            booksList.Add(new Book(56, "Titus"));
            booksList.Add(new Book(57, "Philemon"));
            booksList.Add(new Book(58, "Hebrews"));
            booksList.Add(new Book(59, "James"));
            booksList.Add(new Book(60, "1 Peter"));
            booksList.Add(new Book(61, "2 Peter"));
            booksList.Add(new Book(62, "1 John"));
            booksList.Add(new Book(63, "2 John"));
            booksList.Add(new Book(64, "3 John"));
            booksList.Add(new Book(65, "Jude"));
            booksList.Add(new Book(66, "Revelation"));

            return booksList;
        }

    }

    public class Book
    {
        public Book(int referenceNum, string name)
        {
            this.referenceNum = referenceNum;
            Name = name;
        }

        public int referenceNum { get; set; }
        public String Name { get; set; }

    }
}

Controllers/ApplicationController.cs
using Bible_Application.Models;
using Bible_Application.Services;
using NLog;
using Unity.Injection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unity;

namespace Bible_Application.Controllers
{
    public class ApplicationController : Controller
    {
        // GET: Application
        public ActionResult Home()
        {
            return View("HomeView");
        }

        // GET: Entry Page
        public ActionResult BibleVerseEntry()
        {
            return View("VerseEntryView");
        }

        // GET: Search Page
        public ActionResult BibleVerseSearch()
        {
            return View("VerseSearchView");
        }

        //GET: Submit Search function to return values
        [HttpPost]
        public ActionResult SubmitSearch(BibleDisplayObject displayObject)
        {
            //Dependency Injection for Logger
            UnityContainer container = new UnityContainer();
            container.RegisterType<ILogger, Logger>();
            var logger = container.Resolve<ILogger>();

            logger = LogManager.GetLogger("bibleAppLoggerRules");

            logger.Info("Entered SubmitSearch in Controller");

            try
            {
                searchService search = new searchService();
                displayObject = search.search(displayObject);

                logger.Info("Successfully exiting SubmitSearch in Controller");
                return View("VerseSearchView", displayObject);
            }
            catch (Exception e)
            {

                logger.Error("Exception: " + e.Message);
                return Content(e.Message);
            }
        }

        //GET: Submit Entry to Database
        [HttpPost]
        public ActionResult SubmitEntry(BibleDisplayObject displayObject)
        {
            //Dependency Injection for Logger
            UnityContainer container = new UnityContainer();
            container.RegisterType<ILogger, Logger>();
            var logger = container.Resolve<ILogger>();

            logger = LogManager.GetLogger("bibleAppLoggerRules");

            logger.Info("Entered SubmitEntry in Controller");

            try
            {
                entryService entry = new entryService();
                displayObject = entry.entry(displayObject);

                logger.Info("Successfully exiting SubmitEntry in Controller");

                return View("VerseEntryView", displayObject);
            }
            catch (Exception e)
            {
                logger.Error("Exception: " + e.Message);
                return Content(e.Message);
            }
        }
    }
}

Views/Application/HomeView.cshtml
@{
    ViewBag.Title = "HomeView";
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}

<div class="shadow p-3 mb-5 bg-white rounded">
    <div class="jumbotron">
        <h1 class="display-4">Welcome to Brendan's Bible App!</h1>
        <p class="lead">May the Lord Bless You!</p>
        <hr class="my-4">
        <p>Select a tab up in the NavBar</p>
    </div>
</div>

Views/Application/VerseEntryView.cshtml
@model Bible_Application.Models.BibleDisplayObject

@{
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enter a Verse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Testament, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chapter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chapter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chapter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Verse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Verse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Verse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/Application/VerseSearchView.cshtml
@model Bible_Application.Models.BibleDisplayObject

@{
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}

<h2>Enter the Verse You Would Like To Read!</h2>

@using (Html.BeginForm("SubmitSearch","Application",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Testament, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chapter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chapter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chapter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Verse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Verse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Verse, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="alert alert-info" role="alert">
        @Html.DisplayFor(model => model.VerseText)
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.5.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <title>@Page.Title</title>
    @RenderSection("head", required: false)
</head>
<body>
    <div class="container body-content">
        @RenderPage("_Header.cshtml")
        @RenderBody()
    </div>

    @RenderPage("_Footer.cshtml")
</body>
</html>

Views/Shared/_Footer.cshtml
<style>
    .footer {
        text-align: center;
        width: 100%;
        background-color: #eee;
        margin-top: 32px;
        padding-top: 8px;
        padding-bottom: 8px;
    }
</style>
<div class="footer">
    <h5>Created by Brendan | 2020</h5>
</div>

Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="Home">Bible App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="Home">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="entry">Entry Page</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="search">Search Page</a>
            </li>
        </ul>
    </div>
</nav>
<br />